### ISSUE TITLE
I would like to get simple-array not vector.

### ISSUE THREAD

**Issue by kkazuo** [chaitanyagupta/qbase64#3]
https://github.com/chaitanyagupta/qbase64/blob/2357abaed85453108d1c62a2df1ea97ad1bd47c0/qbase64.lisp#L705

```#lisp
CL-USER> (type-of (qbase64:decode-string "AQAB" :scheme :uri))
(VECTOR (UNSIGNED-BYTE 8) 3)
CL-USER> (type-of (make-array 3 :element-type '(unsigned-byte 8) :initial-contents '(1 0 1)))
(SIMPLE-ARRAY (UNSIGNED-BYTE 8) (3))
```

**Comment by chaitanyagupta** [comment]
Thanks for the report. I have pushed a new release -- now, when DECODE-STRING gets a string that is **NOT** padded, you will get back a SIMPLE-ARRAY.

```cl
CL-USER> (type-of (qbase64:decode-string "AQAB" :scheme :uri))
(SIMPLE-ARRAY (UNSIGNED-BYTE 8) (3))
```

However, if the string is padded, you will get back a displaced array like earlier.

```cl
CL-USER> (type-of (qbase64:decode-string "AQABAA==" :scheme :uri))
(VECTOR (UNSIGNED-BYTE 8) 4)
```

To return a SIMPLE-ARRAY for this latter use case requires some surgery in `DECODE` or `%DECODE`. The best thing you can do right now is to coerce it:

```cl
CL-USER> (type-of (coerce (qbase64:decode-string "AQABAA==" :scheme :uri)
                          '(simple-array (unsigned-byte 8) (*))))
(SIMPLE-ARRAY (UNSIGNED-BYTE 8) (4))
```
